# Apenas Exemplo de como criar um pod com um container que roda um html

apiVersion: v1
kind: Pod
metadata:
  name: app-html
  labels:
    app: app-html
spec:
  containers:
  - name: app-html
    image: marcosteixeira/app-html:1.0
    ports:
    - containerPort: 80
